/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labextra_angelponce;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Familia PM
 */
public class LabExtra_AngelPonce extends javax.swing.JFrame {

    /**
     * Creates new form LabExtra_AngelPonce
     */
    public LabExtra_AngelPonce() {
        initComponents();
    }
    private int helpe = 0;
    private int helpj = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crearequipos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        slogan = new javax.swing.JTextField();
        pais = new javax.swing.JTextField();
        cantidad = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        crearjugadores = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        balones = new javax.swing.JTextField();
        olimpico = new javax.swing.JTextField();
        medallas = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        sex = new javax.swing.JTextField();
        nacionalidad = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        secondname = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        verequiposyjugadores = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlequipos = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jljugadores = new javax.swing.JList<>();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel1.setText("Nombre");

        jLabel2.setText("Slogan");

        jLabel3.setText("Pais de Origen");

        jLabel4.setText("Cantidad de campeonatos ganados");

        jButton3.setText("CREAR EQUIPO");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("aceptar");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel6.setText("EQUIPOS");

        jLabel19.setText("Seleccione uno a la vez y dé click en aceptar para agregar a su equipo");

        javax.swing.GroupLayout crearequiposLayout = new javax.swing.GroupLayout(crearequipos.getContentPane());
        crearequipos.getContentPane().setLayout(crearequiposLayout);
        crearequiposLayout.setHorizontalGroup(
            crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearequiposLayout.createSequentialGroup()
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearequiposLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearequiposLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearequiposLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(crearequiposLayout.createSequentialGroup()
                                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombre)
                                    .addComponent(slogan, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearequiposLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton4)
                                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(crearequiposLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel6)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearequiposLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        crearequiposLayout.setVerticalGroup(
            crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearequiposLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(crearequiposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jLabel7.setText("JUGADORES");

        jLabel8.setText("Nombre");

        jLabel9.setText("Apellido");

        jLabel10.setText("Edad");

        jLabel11.setText("Nacionalidad");

        jLabel12.setText("Sexo");

        jLabel13.setText("Canidad de balones de oro");

        jLabel14.setText("Cantidad de Medallas");

        jLabel15.setText("Atleta Olimpico? (si o no)");

        olimpico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olimpicoActionPerformed(evt);
            }
        });

        jButton5.setText("CREAR JUGADOR");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout crearjugadoresLayout = new javax.swing.GroupLayout(crearjugadores.getContentPane());
        crearjugadores.getContentPane().setLayout(crearjugadoresLayout);
        crearjugadoresLayout.setHorizontalGroup(
            crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearjugadoresLayout.createSequentialGroup()
                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crearjugadoresLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(crearjugadoresLayout.createSequentialGroup()
                                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel15))
                                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crearjugadoresLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(jLabel7))
                                    .addGroup(crearjugadoresLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(balones, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(crearjugadoresLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(olimpico, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel14)
                            .addGroup(crearjugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(crearjugadoresLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(crearjugadoresLayout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton5)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(medallas, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(302, Short.MAX_VALUE)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(92, 92, 92)
                    .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(291, Short.MAX_VALUE)))
        );
        crearjugadoresLayout.setVerticalGroup(
            crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crearjugadoresLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7)
                .addGap(22, 22, 22)
                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(35, 35, 35)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(balones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel14)
                .addGap(29, 29, 29)
                .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(olimpico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crearjugadoresLayout.createSequentialGroup()
                    .addContainerGap(366, Short.MAX_VALUE)
                    .addComponent(medallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(133, 133, 133)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(211, 211, 211)
                    .addComponent(nacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(288, Short.MAX_VALUE)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(161, 161, 161)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(338, Short.MAX_VALUE)))
            .addGroup(crearjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(crearjugadoresLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(secondname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(389, Short.MAX_VALUE)))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Equipos");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        jlequipos.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jlequipos);

        jljugadores.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jljugadores);

        jButton7.setText("eliminar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("modificar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("eliminar");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("modificar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jLabel16.setText("Equipos");

        jLabel17.setText("Jugadores");

        jLabel18.setText("Equipos creados en la historia");

        javax.swing.GroupLayout verequiposyjugadoresLayout = new javax.swing.GroupLayout(verequiposyjugadores.getContentPane());
        verequiposyjugadores.getContentPane().setLayout(verequiposyjugadoresLayout);
        verequiposyjugadoresLayout.setHorizontalGroup(
            verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, verequiposyjugadoresLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, verequiposyjugadoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(114, 114, 114)
                .addComponent(jLabel17)
                .addGap(108, 108, 108))
        );
        verequiposyjugadoresLayout.setVerticalGroup(
            verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(verequiposyjugadoresLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(verequiposyjugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton7)
                    .addComponent(jButton10))
                .addContainerGap(171, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Crear EQuipos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear Jugadores");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton6.setText("Ver equipos/jugadores, eliminar, modificar");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (jugadores.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Primero debe crear jugadores para crear un equipo");
        } else {
            helpe=0;
            players = new ArrayList();
            crearequipos.pack();
            crearequipos.setModal(true);
            crearequipos.setLocationRelativeTo(null);
            crearequipos.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        helpj = 0;
        jButton5.setText("CREAR JUGADORES");
        crearjugadores.pack();
        crearjugadores.setModal(true);
        crearjugadores.setLocationRelativeTo(null);
        crearjugadores.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void olimpicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olimpicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_olimpicoActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked

        if (cb.getSelectedIndex() >= 0) {
            JOptionPane.showMessageDialog(null, "Agregaste a " + cb.getSelectedItem() + " a tu equipo!");
            players.add(cb.getSelectedItem());
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if (helpe == 0) {
            //players = new ArrayList();
            Equipos e = new Equipos(nombre.getText(), slogan.getText(), pais.getText(),
                    Integer.parseInt(cantidad.getText()), players);
            nombre.setText("");
            slogan.setText("");
            pais.setText("");
            cantidad.setText("");
            equipos.add(e);
            JOptionPane.showMessageDialog(null, "Creaste al equipo!");
            DefaultTreeModel m = (DefaultTreeModel) jTree1.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) m.getRoot();
            DefaultMutableTreeNode equipo = new DefaultMutableTreeNode(e.getNombre());
            for (int i = 0; i < players.size(); i++) {
                DefaultMutableTreeNode jug = new DefaultMutableTreeNode(players.get(i));
                equipo.add(jug);
            }
            raiz.add(equipo);
            m.reload();

            DefaultListModel modelo = (DefaultListModel) jlequipos.getModel();
            modelo.addElement(e);
            jlequipos.setModel(modelo);
            File equip = new File("./equipos.txt");
            if (equip.exists()) {
                BufferedWriter bw = null;
                try {
                    bw = new BufferedWriter(new FileWriter(equip, true));
                    bw.write(e.toString());
                    bw.newLine();
                    bw.flush();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Algo salio mal");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe el archivo");
            }
            players = new ArrayList();
        }
        else{
            Equipos e = new Equipos(nombre.getText(), slogan.getText(), pais.getText(),
                    Integer.parseInt(cantidad.getText()), players);
            nombre.setText("");
            slogan.setText("");
            pais.setText("");
            cantidad.setText("");
            equipos.set(jlequipos.getSelectedIndex(), e);
            DefaultListModel modelo = (DefaultListModel) jlequipos.getModel();
            modelo.setElementAt(e, jlequipos.getSelectedIndex());
            jlequipos.setModel(modelo);
            JOptionPane.showMessageDialog(null, "Modificaste al equipo!");
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        if (jlequipos.getSelectedIndex() >= 0) {
            equipos.remove(jlequipos.getSelectedIndex());
            DefaultListModel modelo = (DefaultListModel) jlequipos.getModel();
            modelo.removeElementAt(jlequipos.getSelectedIndex());
            jlequipos.setModel(modelo);

        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        if (jljugadores.getSelectedIndex() >= 0) {
            jugadores.remove(jljugadores.getSelectedIndex());
            DefaultListModel modelo = (DefaultListModel) jljugadores.getModel();
            modelo.removeElementAt(jljugadores.getSelectedIndex());
            jljugadores.setModel(modelo);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        if (jljugadores.getSelectedIndex() >= 0) {
            helpj = 1;
            jButton5.setText("MODIFICAR JUGADOR");
            crearjugadores.pack();
            crearjugadores.setModal(true);
            crearjugadores.setLocationRelativeTo(null);
            crearjugadores.setVisible(true);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        if (helpj == 0) {
            Jugadores j = new Jugadores(name.getText(), secondname.getText(), nacionalidad.getText(),
                    age.getText(), sex.getText(), balones.getText(), medallas.getText(), olimpico.getText());
            jugadores.add(j);
            DefaultListModel modelo = (DefaultListModel) jljugadores.getModel();
            modelo.addElement(j);
            jljugadores.setModel(modelo);
            name.setText("");
            secondname.setText("");
            nacionalidad.setText("");
            age.setText("");
            sex.setText("");
            balones.setText("");
            medallas.setText("");
            olimpico.setText("");
            JOptionPane.showMessageDialog(null, "Creaste un jugador!");
            DefaultComboBoxModel model = (DefaultComboBoxModel) cb.getModel();
            model.addElement(j);
            cb.setModel(model);
            File jugs = new File("./jugadores.txt");
            if (jugs.exists()) {
                BufferedWriter bw = null;
                try {
                    bw = new BufferedWriter(new FileWriter(jugs, true));
                    bw.write(j.toString());
                    bw.newLine();
                    bw.flush();
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Algo salio mal");
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe el archivo");
            }

        } else {
            Jugadores j = new Jugadores(name.getText(), secondname.getText(), nacionalidad.getText(),
                    age.getText(), sex.getText(), balones.getText(), medallas.getText(), olimpico.getText());
            jugadores.set(jljugadores.getSelectedIndex(), j);
            DefaultListModel modelo = (DefaultListModel) jljugadores.getModel();
            modelo.setElementAt(j, jljugadores.getSelectedIndex());
            jljugadores.setModel(modelo);
            name.setText("");
            secondname.setText("");
            nacionalidad.setText("");
            age.setText("");
            sex.setText("");
            balones.setText("");
            medallas.setText("");
            olimpico.setText("");
            JOptionPane.showMessageDialog(null, "Modificaste al jugador!");
        }

    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        verequiposyjugadores.pack();
        verequiposyjugadores.setModal(true);
        verequiposyjugadores.setLocationRelativeTo(null);
        verequiposyjugadores.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        if (jlequipos.getSelectedIndex() >= 0) {
            /*
            helpj = 1;
            jButton5.setText("MODIFICAR JUGADOR");
            crearjugadores.pack();
            crearjugadores.setModal(true);
            crearjugadores.setLocationRelativeTo(null);
            crearjugadores.setVisible(true);
             */
            helpe = 1;
            jButton3.setText("MODIFICAR EQUIPO");
            crearequipos.pack();
            crearequipos.setModal(true);
            crearequipos.setLocationRelativeTo(null);
            crearequipos.setVisible(true);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabExtra_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabExtra_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabExtra_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabExtra_AngelPonce.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabExtra_AngelPonce().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField balones;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JDialog crearequipos;
    private javax.swing.JDialog crearjugadores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTree jTree1;
    private javax.swing.JList<String> jlequipos;
    private javax.swing.JList<String> jljugadores;
    private javax.swing.JTextField medallas;
    private javax.swing.JTextField nacionalidad;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField olimpico;
    private javax.swing.JTextField pais;
    private javax.swing.JTextField secondname;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField slogan;
    private javax.swing.JDialog verequiposyjugadores;
    // End of variables declaration//GEN-END:variables
    ArrayList<Jugadores> jugadores = new ArrayList();
    ArrayList<Equipos> equipos = new ArrayList();
    ArrayList<Object> players = new ArrayList();
}
